export const HOME_ACTION_TYPE = {
    SET_LIST_UPDATE: 'HOME_ACTION_TYPE.SET_LIST_UPDATE',
    SET_LIST_UPDATE_SUCCESS: 'HOME_ACTION_TYPE.SET_LIST_UPDATE_SUCCESS',
    SET_LIST_UPDATE_ERROR: 'HOME_ACTION_TYPE.SET_LIST_UPDATE_ERROR',
  };